[package]
name = "cachefetch"
version = "0.0.2"
edition = "2024"

[dependencies]
byte-unit = "5.1.6"
crossterm = "0.29.0"
ratatui = "0.29.0"

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/{ name }-{ target }-{ version }{ archive-suffix }"
bin-dir = "{ bin }{ binary-ext }"
